### ISSUE TITLE
comma in fractional numbers

### ISSUE THREAD

**Issue by Vlad-Sol** [SecUSo/privacy-friendly-shopping-list#21] opened 2016-12-16 07:40 UTC
Could you, please, make it possible to enter point instead comma in fractional numbers to price field on devices, where locale demand it.

**Comment by Ifill-Brito** [comment] 2016-12-25 17:19
Hi, could you tell us which locale you are using. I have tested the following ones and it behaves as expected:

English  (United States) -> point
Español (Estados Unidos) -> point
Español (España) -> comma
Deutsch (Deutschland) -> comma

if you are getting a diffrent result with one of this locale, then you could maybe let us know the Android version where the problem occurs to check again.

Thanks

**Comment by Vlad-Sol** [comment] 2016-12-25 17:54
Hi,
I use Russian locale on CyanogenMod 12.1
The app aware that it must be point, but refuse to accept it, as you can
see in screenshot

--
Have a nice day, Vlad

25 дек. 2016 г. 19:20 пользователь "Ifill-Brito" <notifications@github.com>
написал:

Hi, could you tell us which locale you are using. I have tested the
following ones and it behaves as expected:

English (United States) -> point
Español (Estados Unidos) -> point
Español (España) -> comma
Deutsch (Deutschland) -> comma

if you are getting a diffrent result with one of this locale, then you
could maybe let us know the Android version where the problem occurs to
check again.

Thanks

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SecUSo/privacy-friendly-shopping-list/issues/21#issuecomment-269130613>,
or mute the thread

**Comment by Ifill-Brito** [comment] 2016-12-25 18:14
Thanks for the information. I could reproduce the problem in my device now. I'm gonna be fixing this in the next days!

**Comment by Yonjuni** [comment] 2016-12-25 20:19
Plus we will add a Russian translation soon ;-)

**Comment by Ifill-Brito** [comment] 2016-12-27 22:31
This bug was present in devices with Android API <= 21. The problem should be fixed now. However you will not see a point when you enter the number. Although you see the app in English, the Russian locale uses commas for numbers. 

The error message (#,###,###.00) was wrong, because the app wasn't expecting a point, but a comma as decimal separator. The real problem was that you could not enter a comma either because we forced points and commas to be replaced by the decimal separator of the locale but it wasn't working because we had a bug there.

If you try to enter point now it will be replaced by a comma immediately. So you will see 3,62 and the OK button will be enabled.

Thanks for reporting this.

**Closed** 2016-12-28 17:05 UTC
Labels: enhancement
